// <auto-generated />
using System;
using Hook.Shared.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hook.Shared.Persistence.Data.Migrations
{
    [DbContext(typeof(HookDbContext))]
    [Migration("20260501173614_AddProviderAvailability")]
    partial class AddProviderAvailability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hook.Features.Geocoding.GeocodeCache.GeocodeCacheEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormattedAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Key");

                    b.ToTable("geocode_cache", (string)null);
                });

            modelBuilder.Entity("Hook.Features.ProviderAvailability.AvailabilityAggregate.ProviderAvailability", b =>
                {
                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormattedAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (Point, 4326)");

                    b.PrimitiveCollection<string>("Services")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<bool>("ShareContact")
                        .HasColumnType("boolean");

                    b.HasKey("Phone");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_provider_availabilities_expires_at");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_provider_availabilities_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.ToTable("provider_availabilities", (string)null);
                });

            modelBuilder.Entity("Hook.Features.ProviderAvailability.Register.RegistrationDraft", b =>
                {
                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DraftFormattedAddress")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<double?>("DraftLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("DraftLongitude")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<string>("DraftServices")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<bool?>("DraftShareContact")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Phone");

                    b.ToTable("provider_registration_drafts", (string)null);
                });

            modelBuilder.Entity("Hook.Features.ServiceTaxonomy.ServiceAggregate.Service", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string>("RawExamples")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("Slug");

                    b.HasIndex("Slug")
                        .HasDatabaseName("ix_services_slug_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Slug"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Slug"), new[] { "gin_trgm_ops" });

                    b.ToTable("services", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
