// <auto-generated />
using System;
using Hook.Shared.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hook.Shared.Persistence.Data.Migrations
{
    [DbContext(typeof(HookDbContext))]
    [Migration("20260524215840_MatchFeedbackConcurrencyVersion")]
    partial class MatchFeedbackConcurrencyVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hook.Features.ChatSession.AccessLog.ChatAccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("ParticipantId")
                        .HasDatabaseName("ix_chat_access_logs_participant");

                    b.ToTable("chat_access_logs", (string)null);
                });

            modelBuilder.Entity("Hook.Features.ChatSession.ParticipantAggregate.ChatParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CurrentSessionId")
                        .HasColumnType("uuid");

                    b.Property<long>("LastInboundSequence")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<byte[]>("PublicKey")
                        .HasMaxLength(200)
                        .HasColumnType("bytea");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .HasDatabaseName("ix_chat_participants_chat_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ux_chat_participants_token");

                    b.ToTable("chat_participants", (string)null);
                });

            modelBuilder.Entity("Hook.Features.ChatSession.SessionAggregate.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("bytea");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChatId", "CreatedAt", "Sequence")
                        .HasDatabaseName("ix_chat_messages_chat_created_seq");

                    b.HasIndex("ChatId", "ParticipantId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_chat_messages_chat_participant_sequence");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("Hook.Features.ChatSession.SessionAggregate.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProductiveSilenceFiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_chat_sessions_expires_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_chat_sessions_status");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("Hook.Features.Feedback.Models.MatchFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("EtaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("NoReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("PromptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RepliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Step1RecheckCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("ix_match_feedback_match");

                    b.HasIndex("PromptedAt")
                        .HasDatabaseName("ix_match_feedback_prompted_at");

                    b.HasIndex("Answer", "PromptedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_match_feedback_pending_prompted_at")
                        .HasFilter("\"Answer\" = 'Pending'");

                    b.HasIndex("MatchId", "Step")
                        .IsUnique()
                        .HasDatabaseName("ux_match_feedback_pending")
                        .HasFilter("\"Answer\" = 'Pending'");

                    b.HasIndex("RequestId", "Step")
                        .IsUnique()
                        .HasDatabaseName("ux_match_feedback_request_step1")
                        .HasFilter("\"Step\" = 'DidYouFind'");

                    b.ToTable("match_feedback", (string)null);
                });

            modelBuilder.Entity("Hook.Features.Feedback.ProviderStatsAggregate.ProviderStats", b =>
                {
                    b.Property<string>("ProviderPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("integer");

                    b.Property<double>("SuccessRate")
                        .HasColumnType("double precision");

                    b.HasKey("ProviderPhone");

                    b.ToTable("provider_stats", (string)null);
                });

            modelBuilder.Entity("Hook.Features.Geocoding.GeocodeCache.GeocodeCacheEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormattedAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Key");

                    b.HasIndex("FetchedAt")
                        .HasDatabaseName("ix_geocode_cache_fetched_at");

                    b.ToTable("geocode_cache", (string)null);
                });

            modelBuilder.Entity("Hook.Features.Matching.MatchAggregate.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ContactShared")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasDefaultValueSql("'Exact'");

                    b.Property<DateTimeOffset?>("PickedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<string>("ServiceSlug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .HasDatabaseName("ix_matches_chat_id")
                        .HasFilter("\"ChatId\" IS NOT NULL");

                    b.HasIndex("ProviderPhone")
                        .HasDatabaseName("ix_matches_provider_phone");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("ix_matches_request_id");

                    b.HasIndex("RequestId", "PickedAt")
                        .HasDatabaseName("ix_matches_request_picked_at");

                    b.HasIndex("RequestId", "ProviderPhone")
                        .IsUnique()
                        .HasDatabaseName("ux_matches_request_provider");

                    b.HasIndex("RequestId", "Score", "DistanceKm", "CreatedAt", "Id")
                        .IsDescending(false, true, false, false, false)
                        .HasDatabaseName("ix_matches_request_score_distance_created_id");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("Hook.Features.MetaTemplates.WhatsappContact", b =>
                {
                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("LastInboundAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Phone");

                    b.HasIndex("LastInboundAt")
                        .HasDatabaseName("ix_whatsapp_contacts_last_inbound_at");

                    b.ToTable("whatsapp_contacts", (string)null);
                });

            modelBuilder.Entity("Hook.Features.ProviderAvailability.AvailabilityAggregate.ProviderAvailability", b =>
                {
                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormattedAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (Point, 4326)");

                    b.PrimitiveCollection<string>("Services")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<bool>("ShareContact")
                        .HasColumnType("boolean");

                    b.HasKey("Phone");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_provider_availabilities_expires_at");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_provider_availabilities_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("Services")
                        .HasDatabaseName("ix_provider_availabilities_services_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Services"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Services"), new[] { "jsonb_path_ops" });

                    b.ToTable("provider_availabilities", (string)null);
                });

            modelBuilder.Entity("Hook.Features.ProviderAvailability.Register.RegistrationDraft", b =>
                {
                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DraftFormattedAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<double?>("DraftLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("DraftLongitude")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<string>("DraftServices")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<bool?>("DraftShareContact")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ResolveStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Phone");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_provider_registration_drafts_updated_at");

                    b.ToTable("provider_registration_drafts", (string)null);
                });

            modelBuilder.Entity("Hook.Features.ServiceRequest.Create.ClientRequestDraft", b =>
                {
                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DraftDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DraftFormattedAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<double?>("DraftLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("DraftLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("DraftServiceSlug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool?>("DraftSharePhoneConsent")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ResolveStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Phone");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_client_request_drafts_updated_at");

                    b.ToTable("client_request_drafts", (string)null);
                });

            modelBuilder.Entity("Hook.Features.ServiceRequest.RequestAggregate.ServiceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoExpandedOnce")
                        .HasColumnType("boolean");

                    b.Property<string>("ClientPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CurrentRadiusKm")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("FormattedAddress")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (Point, 4326)");

                    b.Property<string>("ServiceSlug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("SharePhoneNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.PrimitiveCollection<string>("ShownProviderPhones")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_service_requests_closed_created_at")
                        .HasFilter("\"Status\" = 'Closed'");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_service_requests_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("ClientPhone", "Status")
                        .HasDatabaseName("ix_service_requests_client_phone_status");

                    b.ToTable("service_requests", (string)null);
                });

            modelBuilder.Entity("Hook.Features.ServiceTaxonomy.JudgeParent.JudgeParentDedup", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("JudgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Slug");

                    b.HasIndex("JudgedAt")
                        .HasDatabaseName("ix_judge_parent_dedup_judged_at");

                    b.ToTable("judge_parent_dedup", (string)null);
                });

            modelBuilder.Entity("Hook.Features.ServiceTaxonomy.ServiceAggregate.Service", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParentSlug")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.PrimitiveCollection<string>("RawExamples")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("Slug");

                    b.HasIndex("ParentSlug")
                        .HasDatabaseName("ix_services_parent_slug");

                    b.HasIndex("Slug")
                        .HasDatabaseName("ix_services_slug_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Slug"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Slug"), new[] { "gin_trgm_ops" });

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("Hook.Features.Whatsapp.ReceiveWebhook.AmbiguousIntentDraft", b =>
                {
                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Phone");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_ambiguous_intent_drafts_created_at");

                    b.ToTable("ambiguous_intent_drafts", (string)null);
                });

            modelBuilder.Entity("Hook.Features.ChatSession.AccessLog.ChatAccessLog", b =>
                {
                    b.HasOne("Hook.Features.ChatSession.SessionAggregate.ChatSession", null)
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hook.Features.ChatSession.ParticipantAggregate.ChatParticipant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hook.Features.ChatSession.ParticipantAggregate.ChatParticipant", b =>
                {
                    b.HasOne("Hook.Features.ChatSession.SessionAggregate.ChatSession", null)
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hook.Features.ChatSession.SessionAggregate.ChatMessage", b =>
                {
                    b.HasOne("Hook.Features.ChatSession.SessionAggregate.ChatSession", null)
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hook.Features.Feedback.Models.MatchFeedback", b =>
                {
                    b.HasOne("Hook.Features.Matching.MatchAggregate.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hook.Features.Matching.MatchAggregate.Match", b =>
                {
                    b.HasOne("Hook.Features.ServiceRequest.RequestAggregate.ServiceRequest", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hook.Features.ServiceTaxonomy.ServiceAggregate.Service", b =>
                {
                    b.HasOne("Hook.Features.ServiceTaxonomy.ServiceAggregate.Service", null)
                        .WithMany()
                        .HasForeignKey("ParentSlug")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
